const cst = {
    ADD_BOOKING: "ADD_BOOKING",
    ADD_BOOKING_FAILURE: "ADD_BOOKING_FAILURE",
    ADD_BOOKING_SUCCESS: "ADD_BOOKING_SUCCESS",
    
    ADD_PASSENGER: "ADD_PASSENGER",
    ADD_PASSENGER_FAILURE: "ADD_PASSENGER_FAILURE",
    ADD_PASSENGER_SUCCESS: "ADD_PASSENGER_SUCCESS",
    
    ADD_AIRPLANE: "ADD_AIRPLANE",
    ADD_AIRPLANE_FAILURE: "ADD_AIRPLANE_FAILURE",
    ADD_AIRPLANE_SUCCESS: "ADD_AIRPLANE_SUCCESS",
    
    ADD_FLIGHT: "ADD_FLIGHT",
    ADD_FLIGHT_FAILURE: "ADD_FLIGHT_FAILURE",
    ADD_FLIGHT_SUCCESS: "ADD_FLIGHT_SUCCESS",
    
    UPDATE_BOOKING_STATUS: "UPDATE_BOOKING_STATUS",
    UPDATE_BOOKING_STATUS_FAILURE: "UPDATE_BOOKING_STATUS_FAILURE",
    UPDATE_BOOKING_STATUS_SUCCESS: "UPDATE_BOOKING_STATUS_SUCCESS",
    
    DELETE_BOOKING_BY_ID: "DELETE_BOOKING_BY_ID",
    DELETE_BOOKING_BY_ID_FAILURE: "DELETE_BOOKING_BY_ID_FAILURE",
    DELETE_BOOKING_BY_ID_SUCCESS: "DELETE_BOOKING_BY_ID_SUCCESS",
    
    GET_FLIGHT_INFO: "GET_FLIGHT_INFO",
    GET_FLIGHT_INFO_FAILURE: "GET_FLIGHT_INFO_FAILURE",
    GET_FLIGHT_INFO_SUCCESS: "GET_FLIGHT_INFO_SUCCESS",
    
    GET_BOOKING_BY_ID: "GET_BOOKING_BY_ID",
    GET_BOOKING_BY_ID_FAILURE: "GET_BOOKING_BY_ID_FAILURE",
    GET_BOOKING_BY_ID_SUCCESS: "GET_BOOKING_BY_ID_SUCCESS",
    
    GET_BOOKINGS: "GET_BOOKINGS",
    GET_BOOKINGS_FAILURE: "GET_BOOKINGS_FAILURE",
    GET_BOOKINGS_SUCCESS: "GET_BOOKINGS_SUCCESS",
    
    GET_INFO_4_BOOKING: "GET_INFO_4_BOOKING",
    GET_INFO_4_BOOKING_FAILURE: "GET_INFO_4_BOOKING_FAILURE",
    GET_INFO_4_BOOKING_SUCCESS: "GET_INFO_4_BOOKING_SUCCESS",
    
    GET_PASSENGER_BY_ID: "GET_PASSENGER_BY_ID",
    GET_PASSENGER_BY_ID_FAILURE: "GET_PASSENGER_BY_ID_FAILURE",
    GET_PASSENGER_BY_ID_SUCCESS: "GET_PASSENGER_BY_ID_SUCCESS",
    
    GET_PASSENGERS: "GET_PASSENGERS",
    GET_PASSENGERS_FAILURE: "GET_PASSENGERS_FAILURE",
    GET_PASSENGERS_SUCCESS: "GET_PASSENGERS_SUCCESS",
    
    MENU_ADD: "MENU_ADD",
    MENU_DISPLAY: "MENU_DISPLAY",
    MENU_NEUTRAL: "MENU_NEUTRAL"
}

export default cst