module.exports = {
	CLASS_FIRST: "First",
	CLASS_BUSINESS: "Business",
	CLASS_ECONOMY: "Ecomony",
	
	PAY_METHOD_CARD: "Credit Card",
	PAY_METHOD_CHECK: "Check",
	
	PAY_STATUS_SUCCESS: "STATUS_SUCCESS",
	PAY_STATUS_FAILURE: "STATUS_FAILURE",
	
	TICKET_TYPE_MONEY_BACK: "Getting Your Money Back",
	TICKET_TYPE_ONE_WAY: "Fly One Way",
	TICKET_TYPE_LUX: "Fly Luxuriously",
	TICKET_TYPE_COACH: "Coach and Business Class",
	
	BOOKING_STATUS_PRE: "PRE-BOOK",
	BOOKING_STATUS_PENDING: "PENDING",
	BOOKING_STATUS_RESERVED: "RESERVED",
	BOOKING_STATUS_DEPOSIT: "DEPOSIT",
	BOOKING_STATUS_PAID: "PAID",
	BOOKING_STATUS_WAITING: "WAITING",
	BOOKING_STATUS_CANCELLED: "CANCELLED",
	BOOKING_STATUS_VOID: "VOID",
	
	DESTINATION_NY: "New-York",
	DESTINATION_SF: "San Francisco"
}